"""initial_schema_jobs_items_sellers

Revision ID: 118eb978cfda
Revises: 
Create Date: 2026-05-27 21:54:00.048447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '118eb978cfda'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('seller_id', sa.String(length=20), nullable=False),
    sa.Column('store_name', sa.String(length=255), nullable=True),
    sa.Column('marketplace_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seller_id')
    )
    op.create_index(op.f('ix_seller_connections_user_id'), 'seller_connections', ['user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('progress_phase', sa.String(length=30), nullable=True),
    sa.Column('marketplace', sa.String(length=5), nullable=False),
    sa.Column('domain_id', sa.SmallInteger(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('detected_id_column', sa.String(length=100), nullable=True),
    sa.Column('detected_cost_column', sa.String(length=100), nullable=True),
    sa.Column('detected_id_type', sa.String(length=20), nullable=True),
    sa.Column('seller_connection_id', sa.UUID(), nullable=True),
    sa.Column('check_restrictions', sa.Boolean(), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('processed_items', sa.Integer(), nullable=False),
    sa.Column('matched_items', sa.Integer(), nullable=False),
    sa.Column('profitable_items', sa.Integer(), nullable=False),
    sa.Column('restricted_items', sa.Integer(), nullable=False),
    sa.Column('error_items', sa.Integer(), nullable=False),
    sa.Column('fulfillment_type', sa.String(length=5), nullable=False),
    sa.Column('prep_cost_per_item', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('shipping_to_amazon', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('processing_speed', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_connection_id'], ['seller_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('job_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('input_row', sa.Integer(), nullable=False),
    sa.Column('input_id', sa.String(length=50), nullable=False),
    sa.Column('input_id_type', sa.String(length=10), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('asin', sa.String(length=10), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('sales_rank', sa.Integer(), nullable=True),
    sa.Column('buy_box_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('buy_box_seller', sa.String(length=255), nullable=True),
    sa.Column('amazon_is_seller', sa.Boolean(), nullable=False),
    sa.Column('seller_count', sa.Integer(), nullable=False),
    sa.Column('fba_fee', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('referral_fee_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('multipack_qty', sa.SmallInteger(), nullable=False),
    sa.Column('is_hazmat', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('list_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimated_sale_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('roi_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('margin_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('marketplace_fees', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('shipping_cost', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('prep_cost', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('return_reserve', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('can_sell', sa.Boolean(), nullable=True),
    sa.Column('restriction_reason', sa.String(length=50), nullable=True),
    sa.Column('restriction_message', sa.Text(), nullable=True),
    sa.Column('sp_api_total_fees', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sp_api_referral_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sp_api_fba_fee', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('monthly_sold', sa.Integer(), nullable=True),
    sa.Column('sales_rank_drops_30', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('buy_box_is_amazon', sa.Boolean(), nullable=False),
    sa.Column('offer_count_new', sa.SmallInteger(), nullable=True),
    sa.Column('offer_count_used', sa.SmallInteger(), nullable=True),
    sa.Column('trade_in_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('out_of_stock_pct_90', sa.SmallInteger(), nullable=True),
    sa.Column('velocity_score', sa.SmallInteger(), nullable=True),
    sa.Column('risk_score', sa.SmallInteger(), nullable=True),
    sa.Column('competition_hhi', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('sales_per_day', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('estimated_days_to_sell', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_items_asin'), 'job_items', ['asin'], unique=False)
    op.create_index(op.f('ix_job_items_job_id'), 'job_items', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_items_job_id'), table_name='job_items')
    op.drop_index(op.f('ix_job_items_asin'), table_name='job_items')
    op.drop_table('job_items')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_seller_connections_user_id'), table_name='seller_connections')
    op.drop_table('seller_connections')
    # ### end Alembic commands ###
