"""add_users_products_tables_and_fks

Revision ID: 3b1c8eb7194f
Revises: fa9dae3a3707
Create Date: 2026-05-27 23:27:43.818415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b1c8eb7194f'
down_revision: Union[str, Sequence[str], None] = 'fa9dae3a3707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('asin', sa.String(length=10), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('product_type', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=100), nullable=True),
    sa.Column('buy_box_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('list_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sales_rank', sa.Integer(), nullable=True),
    sa.Column('monthly_sold', sa.Integer(), nullable=True),
    sa.Column('sales_rank_drops_30', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('referral_fee_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('fba_fulfillment_fee', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('seller_count', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('parent_asin', sa.String(length=10), nullable=True),
    sa.Column('upc', sa.String(length=15), nullable=True),
    sa.Column('is_hazmat', sa.Boolean(), nullable=False),
    sa.Column('is_adult_product', sa.Boolean(), nullable=False),
    sa.Column('analysis_count', sa.Integer(), nullable=False),
    sa.Column('keepa_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('spapi_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('asin')
    )
    op.create_index(op.f('ix_products_upc'), 'products', ['upc'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supabase_id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('scans_used_month', sa.Integer(), nullable=False),
    sa.Column('scans_limit_month', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_supabase_id'), 'users', ['supabase_id'], unique=True)
    op.add_column('job_items', sa.Column('product_asin', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_job_items_product_asin'), 'job_items', ['product_asin'], unique=False)
    op.create_foreign_key(None, 'job_items', 'products', ['product_asin'], ['asin'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_items', type_='foreignkey')
    op.drop_index(op.f('ix_job_items_product_asin'), table_name='job_items')
    op.drop_column('job_items', 'product_asin')
    op.drop_index(op.f('ix_users_supabase_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_upc'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
