"""add_scan_mode_and_fba_eligible

Revision ID: 612154c12137
Revises: 118eb978cfda
Create Date: 2026-05-27 22:02:44.074699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '612154c12137'
down_revision: Union[str, Sequence[str], None] = '118eb978cfda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('scan_mode', sa.String(length=10), nullable=False, server_default='fast'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'scan_mode')
    # ### end Alembic commands ###
