"""add_cost_profiles

Revision ID: 71e0299f9446
Revises: a987895f55a5
Create Date: 2026-05-28 23:51:53.535039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71e0299f9446'
down_revision: Union[str, Sequence[str], None] = 'a987895f55a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('marketplace', sa.String(length=5), nullable=False),
    sa.Column('fulfillment_type', sa.String(length=5), nullable=False),
    sa.Column('fba_prep_cost', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('fba_shipping_to_amazon', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('mfn_prep_cost', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('mfn_shipping_to_customer', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('mfn_packaging_cost', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_profiles_user_id'), 'cost_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cost_profiles_user_id'), table_name='cost_profiles')
    op.drop_table('cost_profiles')
    # ### end Alembic commands ###
