"""add_dual_fba_mfn_fields

Revision ID: a987895f55a5
Revises: d5099d79105c
Create Date: 2026-05-28 00:46:14.263991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a987895f55a5'
down_revision: Union[str, Sequence[str], None] = 'd5099d79105c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_items', sa.Column('fba_profit', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('job_items', sa.Column('fba_roi_pct', sa.Numeric(precision=8, scale=4), nullable=True))
    op.add_column('job_items', sa.Column('fba_margin_pct', sa.Numeric(precision=8, scale=4), nullable=True))
    op.add_column('job_items', sa.Column('fba_total_fees', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('job_items', sa.Column('mfn_profit', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('job_items', sa.Column('mfn_roi_pct', sa.Numeric(precision=8, scale=4), nullable=True))
    op.add_column('job_items', sa.Column('mfn_margin_pct', sa.Numeric(precision=8, scale=4), nullable=True))
    op.add_column('job_items', sa.Column('mfn_total_fees', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('job_items', sa.Column('best_scenario', sa.String(length=10), nullable=True))
    op.add_column('jobs', sa.Column('fba_prep_cost', sa.Numeric(precision=8, scale=2), nullable=False, server_default='0'))
    op.add_column('jobs', sa.Column('fba_shipping_to_amazon', sa.Numeric(precision=8, scale=2), nullable=False, server_default='0'))
    op.add_column('jobs', sa.Column('mfn_prep_cost', sa.Numeric(precision=8, scale=2), nullable=False, server_default='0'))
    op.add_column('jobs', sa.Column('mfn_shipping_to_customer', sa.Numeric(precision=8, scale=2), nullable=False, server_default='0'))
    op.add_column('jobs', sa.Column('mfn_packaging_cost', sa.Numeric(precision=8, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'mfn_packaging_cost')
    op.drop_column('jobs', 'mfn_shipping_to_customer')
    op.drop_column('jobs', 'mfn_prep_cost')
    op.drop_column('jobs', 'fba_shipping_to_amazon')
    op.drop_column('jobs', 'fba_prep_cost')
    op.drop_column('job_items', 'best_scenario')
    op.drop_column('job_items', 'mfn_total_fees')
    op.drop_column('job_items', 'mfn_margin_pct')
    op.drop_column('job_items', 'mfn_roi_pct')
    op.drop_column('job_items', 'mfn_profit')
    op.drop_column('job_items', 'fba_total_fees')
    op.drop_column('job_items', 'fba_margin_pct')
    op.drop_column('job_items', 'fba_roi_pct')
    op.drop_column('job_items', 'fba_profit')
    # ### end Alembic commands ###
