"""add_pg_job_queue_columns

Revision ID: b583e0af2357
Revises: 71e0299f9446
Create Date: 2026-05-29 01:15:23.380898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b583e0af2357'
down_revision: Union[str, Sequence[str], None] = '71e0299f9446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('locked_by', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_jobs_queue', 'jobs', ['status', 'queued_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'locked_at')
    op.drop_column('jobs', 'locked_by')
    op.drop_column('jobs', 'queued_at')
    # ### end Alembic commands ###
