"""encrypt_refresh_token_column

Revision ID: c6eb8eed3438
Revises: 612154c12137
Create Date: 2026-05-27 22:27:36.424802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6eb8eed3438'
down_revision: Union[str, Sequence[str], None] = '612154c12137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller_connections', sa.Column('refresh_token_encrypted', sa.Text(), nullable=False))
    op.drop_column('seller_connections', 'refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller_connections', sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('seller_connections', 'refresh_token_encrypted')
    # ### end Alembic commands ###
