"""add_fba_eligible

Revision ID: d5099d79105c
Revises: da6f2f66ad61
Create Date: 2026-05-28 00:16:07.292559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5099d79105c'
down_revision: Union[str, Sequence[str], None] = 'da6f2f66ad61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_items', sa.Column('fba_eligible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_items', 'fba_eligible')
    # ### end Alembic commands ###
